
## Jenkins CI/CD
Vagrant.configure("2") do |config|
  config.vm.hostname = "jenkins"
  config.vm.box = "ubuntu/focal64"
  config.vm.network "private_network", ip: "192.168.56.101"
  config.vm.provision "shell", inline: <<-SHELL
    mkdir -p /home/vagrant/.ssh
    cat /vagrant/jenkinskey.pub >> /home/vagrant/.ssh/authorized_keys
    chmod 700 /home/vagrant/.ssh
    chmod 600 /home/vagrant/.ssh/authorized_keys
  SHELL
  config.vm.provider :virtualbox do |virtualbox, override|
    virtualbox.cpus = 4
    virtualbox.memory = 4096
    virtualbox.customize ["modifyvm", :id, "--cpu-profile", "host"]
    virtualbox.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
    virtualbox.customize ["modifyvm", :id, "--nat-localhostreachable1", "on"]
    virtualbox.customize ["modifyvm", :id, "--graphicscontroller", "vboxsvga"]
    virtualbox.customize ["modifyvm", :id, "--accelerate3d", "off"]
    virtualbox.name = "jenkins-cicd"
    override.vm.synced_folder "./", "/vagrant"
  end
end
