provider: virtualbox # options: virtualbox, libvirt, vmware_desktop, hyperv
num_vms: 1 # number of machines
subnet: 192.168.56 # base subnet for private networking
default_ram: 4096 # default RAM in MB
default_cpus: 2 # default CPU cores

roles:
  - hostname: node01
    role: k8s
    ram: 8192
    cpus: 8
