apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-deployment
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: boardgame
          image: akshay2642005/boardshack:staging
          resources:
            requests:
              cpu: "300m"
              memory: "512Mi"
            limits:
              cpu: "750m"
              memory: "1Gi"
