apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-kiali-cert
  namespace: istio-system
spec:
  secretName: isito-kiali-cert
  issuerRef:
    name: mkcert-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - "kiali.istio.home.clcreative.de"
  privateKey:
    rotationPolicy: Always
