apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-deployment
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: boardgame
          image: akshay2642005/boardshack:staging
