apiVersion: v1
kind: Service
metadata:
  name: boardgame-service
  labels:
    app: boardgame
spec:
  selector:
    app: boardgame
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
